# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: v2rayA.v2rayA
PackageVersion: 2.2.5
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/v2rayA/v2rayA/releases/download/v2.2.5/installer_windows_inno_x64_2.2.5.exe
  InstallerSha256: ED1F8AE9F2F8095B7CA8CF6F293AB39DF95B16B9EDE35094F11923096E389B14
- Architecture: arm64
  InstallerUrl: https://github.com/v2rayA/v2rayA/releases/download/v2.2.5/installer_windows_inno_arm64_2.2.5.exe
  InstallerSha256: 83F2CB0CAB1898C9CF866AD776BF4D71F9388775E8C641E6855C01511BCE4F0D
ManifestType: installer
ManifestVersion: 1.6.0
