# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: v2rayA.v2rayA
PackageVersion: 2.2.4.4
InstallerType: inno
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/v2rayA/v2rayA/releases/download/v2.2.4.4/installer_windows_inno_x64_2.2.4.4.exe
  InstallerSha256: AFA53D8A198145C72F40A6461EC8ACF6E8070589E34BE46AE609BFC5E5E8138C
- Architecture: arm64
  InstallerUrl: https://github.com/v2rayA/v2rayA/releases/download/v2.2.4.4/installer_windows_inno_arm64_2.2.4.4.exe
  InstallerSha256: 448DCBBA100E8EB5727768AE21CF16C228ED2936F70BC798165F9F5C494054B8
ManifestType: installer
ManifestVersion: 1.5.0
